---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
upload_dir: static/assets/cms
public_path: "/assets/cms"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: gridsome build
  publish_command: vuepress build -d .vuepress/dist
  preview_output_directory: ".dist"
  output_directory: ".vuepress/dist"
