---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
  templates:
  - blog-post
upload_dir: static/assets/cms
public_path: "/assets/cms"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: gridsome develop -p 8080 -h 0.0.0.0
  publish_command: gridsome build
  preview_output_directory: dist
  output_directory: dist
  instant_preview_command: vuepress dev -p 8080 -h 0.0.0.0
